# Generated by Django 5.1.7 on 2025-07-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_crud', '0004_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, to='backend_crud.skill'),
        ),
    ]
